import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'

import { Layout } from '@/components/Layout'
import { RegisterModal } from '@/components/Modal/RegisterModal'
import { LoginModal } from '@/components/Modal/LoginModal'
import { EditModal } from '@/components/Modal/EditModal'
import '../styles/globals.css'

import SWRProvider from '@/providers/swrProvider'

export const metadata: Metadata = {
  title: 'Twitter Clone',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
  params: any
}>) {
  return (
    <html lang='pt-BR'>
      <body className='h-screen bg-black'>
          <SWRProvider>
            <Toaster />
            <LoginModal />
            <RegisterModal />
            <EditModal />
            <Layout>{children}</Layout>
          </SWRProvider>
      </body>
    </html>
  )
}
