import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Twitter Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className='h-screen bg-black'>{children}</body>
    </html>
  );
}
